In [1]:
import numpy as np

In [2]:
a = np.array([[1,4], [3,1]])

In [3]:
a

array([[1, 4],
       [3, 1]])

In [4]:
a.sort(axis=1)

In [5]:
a

array([[1, 4],
       [1, 3]])

In [6]:
a.sort(axis=0)

In [7]:
a

array([[1, 3],
       [1, 4]])

In [8]:
a = np.array([('a', 2), ('c', 1)], dtype=[('x', 'S1'), ('y', int)])

In [9]:
a

array([(b'a', 2), (b'c', 1)], dtype=[('x', 'S1'), ('y', '<i4')])

In [10]:
a.sort(order='y')

In [11]:
a

array([(b'c', 1), (b'a', 2)], dtype=[('x', 'S1'), ('y', '<i4')])

In [12]:
a.sort(order='x')

In [13]:
a

array([(b'a', 2), (b'c', 1)], dtype=[('x', 'S1'), ('y', '<i4')])